name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image and Push to Hub
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s); docker push grantbenr/hackathon_spring2025:my-image-name:$(date +%s)
